### ISSUE TITLE
Update link with updated  geoJson feature collection.

### ISSUE THREAD

**Issue by jitendra3109** [PGWelch/speedregions#1]
[This document is obsolete. Please see RFC 7946 instead.](http://geojson.org/geojson-spec.html#feature-collection-objects)

> to 

[ The GeoJSON Format](https://tools.ietf.org/html/rfc7946)

**Comment by PGWelch** [comment]
Probably best to include both links. The outdated document is actually a lot easier to read than the up-to-date one.

**Comment by jitendra3109** [comment]
That would be fine! I think this issue should be closed.
